import React, { useState, useEffect } from "react"
import Head from "next/head"
import { FcTimeline } from "react-icons/fc"
import { RiSunFill, RiSunLine } from "react-icons/ri"

const Layout = ({ children, title = "Country Rank" }) => {
  const [theme, setTheme] = useState("")

  useEffect(() => {
    if (typeof window !== "undefined") {
      if (localStorage.getItem("theme") === "dark") {
        document.querySelector("body").classList.add("dark")
        setTheme("dark")
      }
    }
  }, [])

  const handleThemeChange = (theme) => {
    if (theme === "dark") {
      setTheme("dark")
      localStorage.setItem("theme", "dark")
      document.querySelector("body").classList.add("dark")
    } else {
      setTheme("light")
      localStorage.setItem("theme", "light")
      document.querySelector("body").classList.remove("dark")
    }
  }

  return (
    <div className="container mx-auto px-5 md:px-10 xl:px-0">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="flex items-center justify-center">
        <FcTimeline className="text-6xl" />
        <h2 className="mx-3 text-2xl sm:text-4xl">Country Rank</h2>
        <div>
          {theme === "dark" ? (
            <RiSunLine
              className="text-3xl cursor-pointer"
              onClick={() => handleThemeChange("light")}
            />
          ) : (
            <RiSunFill
              className="text-3xl text-black cursor-pointer"
              onClick={() => handleThemeChange("dark")}
            />
          )}
        </div>
      </header>
      <main>{children}</main>
      <footer className="h-16 p-2 text-center">haydar.cayir @ gmail.com</footer>
    </div>
  )
}

export default Layout
